### ISSUE TITLE
Throws-clause in method declarations

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#17]
Exercise 3.29. Modify the Parser to deal with a throws-clause in method declarations.

**Comment by tjsg1992** [comment]
Start within Parser.memberDecl() [line 546]
Add throws checking for each of the three branches, and maybe a new method to parse it. Then, upon creating a new JMethodDeclaration, add as a new argument an array of qualifiedIdentifiers to pass. Then figure out what to do with that inside of the JMethodDeclaration class.

**Comment by cresse** [comment]
I added some really basic pseudocode to plan out this part, but didn't implement anything since the other throws thing comes first.
Besides the two uses in Parser's memberDecl method, JMethodDeclaration also shows up in JavaCCParser.java (L429), so we need to be sure we change that when we change JMethodDeclaration to accept the structure with exceptions in it.

**Comment by cresse** [comment]
this now works for methods and constructors. i think this is done.
